# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - ".*"

  profile: assertive
  review_status: true

  high_level_summary: true
