reviews:
  auto_review:
    enabled: true
    drafts: true
  base_branches:
    - main
    - develop
    - "feature/*"
    - "fix/*"
    - "add/*"
  tone: assertive
  review_status: true

analysis:
  enabled: true
  depth: deep

summary:
  enabled: true

style:
  severity_labels: true
  inline_comments: true
